name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Git and tar
      run: |
        sudo apt update
        sudo apt install -y git tar

    - name: Clone project manually
      run: |
        git clone https://github.com/${{ github.repository }} .
        ls -la

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tar zip unzip openjdk-17-jdk python3-pip \
        python3-setuptools python3-wheel build-essential \
        libffi-dev libssl-dev libncurses5-dev libsqlite3-dev \
        libjpeg-dev libfreetype6-dev zlib1g-dev curl
       pip install --upgrade pip setuptools wheel cython buildozer
       echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -O https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip -d tools

        yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Cek isi buildozer.spec
      run: cat buildozer.spec

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/tools/bin:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kalkulator-google
        path: bin/*.apk
